check publish npm with github package

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -9,39 +9,37 @@ jobs:
     # if: startsWith(github.ref, 'refs/tags/v')
     runs-on: ubuntu-latest
     permissions:
-      id-token: write # Required for OIDC
       contents: read
-    env:
-      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      packages: write
     steps:
       - uses: actions/checkout@v5
       # Setup .npmrc file to publish to GitHub Packages
       - uses: actions/setup-node@v5
         with:
           node-version: 20
-          registry-url: "https://registry.npmjs.org"
+          registry-url: "https://npm.pkg.github.com"
           # Defaults to the user or organization that owns the workflow file
           scope: "@nmcore"
 
-      # Check secrets NODE_AUTH_TOKEN is available
-      - name: Check NODE_AUTH_TOKEN secret
-        run: |
-          if [ -z "$NODE_AUTH_TOKEN" ]; then
-            echo "Error: NODE_AUTH_TOKEN secret is not set."
-            exit 1
-          fi
+      # # Check secrets NODE_AUTH_TOKEN is available
+      # - name: Check NODE_AUTH_TOKEN secret
+      #   run: |
+      #     if [ -z "$NODE_AUTH_TOKEN" ]; then
+      #       echo "Error: NODE_AUTH_TOKEN secret is not set."
+      #       exit 1
+      #     fi
 
-      - name: Set up NPM auth token
-        run: |
-          cat >> ~/.npmrc <<EOF
-          //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
-          registry=https://registry.npmjs.org/
-          always-auth=true
-          EOF
+      # - name: Set up NPM auth token
+      #   run: |
+      #     cat >> ~/.npmrc <<EOF
+      #     //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
+      #     registry=https://registry.npmjs.org/
+      #     always-auth=true
+      #     EOF
 
-      # Read .npmrc file for debugging
-      - name: Read .npmrc file
-        run: cat ~/.npmrc
+      # # Read .npmrc file for debugging
+      # - name: Read .npmrc file
+      #   run: cat ~/.npmrc
 
       # - run: npm ci
 
@@ -69,6 +67,6 @@ jobs:
 
       # Publish to NPM
       - name: Publish to NPM
-        run: npm publish --provenance --access public
+        run: npm publish
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
